package com.wsntools.iris.packageDecode.testClasses;
/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'Test_Union'
 * message type.
 */

public class Test_Union extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 2;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 24;

    /** Create a new Test_Union of size 2. */
    public Test_Union() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new Test_Union of the given data_length. */
    public Test_Union(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_Union with the given data_length
     * and base offset.
     */
    public Test_Union(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_Union using the given byte array
     * as backing store.
     */
    public Test_Union(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_Union using the given byte array
     * as backing store, with the given base offset.
     */
    public Test_Union(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_Union using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public Test_Union(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_Union embedded in the given message
     * at the given base offset.
     */
    public Test_Union(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_Union embedded in the given message
     * at the given base offset and length.
     */
    public Test_Union(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <Test_Union> \n";
      try {
        s += "  [test.value1=0x"+Long.toHexString(get_test_value1())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [test.value2=0x"+Long.toHexString(get_test_value2())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: test.value1
    //   Field type: short
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'test.value1' is signed (false).
     */
    public static boolean isSigned_test_value1() {
        return false;
    }

    /**
     * Return whether the field 'test.value1' is an array (false).
     */
    public static boolean isArray_test_value1() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'test.value1'
     */
    public static int offset_test_value1() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'test.value1'
     */
    public static int offsetBits_test_value1() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'test.value1'
     */
    public short get_test_value1() {
        return (short)getSIntBEElement(offsetBits_test_value1(), 16);
    }

    /**
     * Set the value of the field 'test.value1'
     */
    public void set_test_value1(short value) {
        setSIntBEElement(offsetBits_test_value1(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'test.value1'
     */
    public static int size_test_value1() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'test.value1'
     */
    public static int sizeBits_test_value1() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: test.value2
    //   Field type: byte
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'test.value2' is signed (false).
     */
    public static boolean isSigned_test_value2() {
        return false;
    }

    /**
     * Return whether the field 'test.value2' is an array (false).
     */
    public static boolean isArray_test_value2() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'test.value2'
     */
    public static int offset_test_value2() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'test.value2'
     */
    public static int offsetBits_test_value2() {
        return 0;
    }

    /**
     * Return the value (as a byte) of the field 'test.value2'
     */
    public byte get_test_value2() {
        return (byte)getSIntBEElement(offsetBits_test_value2(), 8);
    }

    /**
     * Set the value of the field 'test.value2'
     */
    public void set_test_value2(byte value) {
        setSIntBEElement(offsetBits_test_value2(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'test.value2'
     */
    public static int size_test_value2() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'test.value2'
     */
    public static int sizeBits_test_value2() {
        return 8;
    }

}
