package mote.sending;
/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'Test_StructInUnion'
 * message type.
 */

public class Test_StructInUnion extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 2;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 126;

    /** Create a new Test_StructInUnion of size 2. */
    public Test_StructInUnion() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new Test_StructInUnion of the given data_length. */
    public Test_StructInUnion(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_StructInUnion with the given data_length
     * and base offset.
     */
    public Test_StructInUnion(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_StructInUnion using the given byte array
     * as backing store.
     */
    public Test_StructInUnion(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_StructInUnion using the given byte array
     * as backing store, with the given base offset.
     */
    public Test_StructInUnion(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_StructInUnion using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public Test_StructInUnion(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_StructInUnion embedded in the given message
     * at the given base offset.
     */
    public Test_StructInUnion(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_StructInUnion embedded in the given message
     * at the given base offset and length.
     */
    public Test_StructInUnion(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <Test_StructInUnion> \n";
      try {
        s += "  [testUnion.testItem1.value=0x"+Long.toHexString(get_testUnion_testItem1_value())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [testUnion.testItem2.value=0x"+Long.toHexString(get_testUnion_testItem2_value())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: testUnion.testItem1.value
    //   Field type: short
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'testUnion.testItem1.value' is signed (false).
     */
    public static boolean isSigned_testUnion_testItem1_value() {
        return false;
    }

    /**
     * Return whether the field 'testUnion.testItem1.value' is an array (false).
     */
    public static boolean isArray_testUnion_testItem1_value() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'testUnion.testItem1.value'
     */
    public static int offset_testUnion_testItem1_value() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'testUnion.testItem1.value'
     */
    public static int offsetBits_testUnion_testItem1_value() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'testUnion.testItem1.value'
     */
    public short get_testUnion_testItem1_value() {
        return (short)getSIntBEElement(offsetBits_testUnion_testItem1_value(), 16);
    }

    /**
     * Set the value of the field 'testUnion.testItem1.value'
     */
    public void set_testUnion_testItem1_value(short value) {
        setSIntBEElement(offsetBits_testUnion_testItem1_value(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'testUnion.testItem1.value'
     */
    public static int size_testUnion_testItem1_value() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'testUnion.testItem1.value'
     */
    public static int sizeBits_testUnion_testItem1_value() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: testUnion.testItem2.value
    //   Field type: short
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'testUnion.testItem2.value' is signed (false).
     */
    public static boolean isSigned_testUnion_testItem2_value() {
        return false;
    }

    /**
     * Return whether the field 'testUnion.testItem2.value' is an array (false).
     */
    public static boolean isArray_testUnion_testItem2_value() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'testUnion.testItem2.value'
     */
    public static int offset_testUnion_testItem2_value() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'testUnion.testItem2.value'
     */
    public static int offsetBits_testUnion_testItem2_value() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'testUnion.testItem2.value'
     */
    public short get_testUnion_testItem2_value() {
        return (short)getSIntBEElement(offsetBits_testUnion_testItem2_value(), 16);
    }

    /**
     * Set the value of the field 'testUnion.testItem2.value'
     */
    public void set_testUnion_testItem2_value(short value) {
        setSIntBEElement(offsetBits_testUnion_testItem2_value(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'testUnion.testItem2.value'
     */
    public static int size_testUnion_testItem2_value() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'testUnion.testItem2.value'
     */
    public static int sizeBits_testUnion_testItem2_value() {
        return 16;
    }

}
