package mote.sending;
/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'Test_ArrayValue'
 * message type.
 */

public class Test_ArrayValue extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 10;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 121;

    /** Create a new Test_ArrayValue of size 10. */
    public Test_ArrayValue() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new Test_ArrayValue of the given data_length. */
    public Test_ArrayValue(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_ArrayValue with the given data_length
     * and base offset.
     */
    public Test_ArrayValue(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_ArrayValue using the given byte array
     * as backing store.
     */
    public Test_ArrayValue(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_ArrayValue using the given byte array
     * as backing store, with the given base offset.
     */
    public Test_ArrayValue(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_ArrayValue using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public Test_ArrayValue(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_ArrayValue embedded in the given message
     * at the given base offset.
     */
    public Test_ArrayValue(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new Test_ArrayValue embedded in the given message
     * at the given base offset and length.
     */
    public Test_ArrayValue(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <Test_ArrayValue> \n";
      try {
        s += "  [value16=";
        for (int i = 0; i < 5; i++) {
          s += "0x"+Long.toHexString(getElement_value16(i) & 0xffff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: value16
    //   Field type: short[], signed
    //   Offset (bits): 0
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'value16' is signed (true).
     */
    public static boolean isSigned_value16() {
        return true;
    }

    /**
     * Return whether the field 'value16' is an array (true).
     */
    public static boolean isArray_value16() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'value16'
     */
    public static int offset_value16(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 5) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'value16'
     */
    public static int offsetBits_value16(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 5) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'value16' as a short[]
     */
    public short[] get_value16() {
        short[] tmp = new short[5];
        for (int index0 = 0; index0 < numElements_value16(0); index0++) {
            tmp[index0] = getElement_value16(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'value16' from the given short[]
     */
    public void set_value16(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_value16(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'value16'
     */
    public short getElement_value16(int index1) {
        return (short)getSIntBEElement(offsetBits_value16(index1), 16);
    }

    /**
     * Set an element of the array 'value16'
     */
    public void setElement_value16(int index1, short value) {
        setSIntBEElement(offsetBits_value16(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'value16'
     */
    public static int totalSize_value16() {
        return (80 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'value16'
     */
    public static int totalSizeBits_value16() {
        return 80;
    }

    /**
     * Return the size, in bytes, of each element of the array 'value16'
     */
    public static int elementSize_value16() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'value16'
     */
    public static int elementSizeBits_value16() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'value16'
     */
    public static int numDimensions_value16() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'value16'
     */
    public static int numElements_value16() {
        return 5;
    }

    /**
     * Return the number of elements in the array 'value16'
     * for the given dimension.
     */
    public static int numElements_value16(int dimension) {
      int array_dims[] = { 5,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
